vorg.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

## Environment Properties
minecraft_version=1.20.1
minecraft_version_range=[1.20.1,1.21)
forge_version=47.4.16
forge_version_range=[47,)
loader_version_range=[47,)
mapping_channel=parchment
mapping_version=2023.09.03-1.20.1


## Mod Properties
mod_id=selective_vanish
mod_name=Selective Vanish
mod_license=GNU General Public License v3.0 (GPLv3)
mod_version=1.0.0
mod_group_id=net.kamkeyke
mod_authors=Kamkeyke

mod_description=SVanish is a VanishMod add-on that enables Selective Vanish. Using the /sv command, you can precisely control which players can see through someone's vanishing. More information can be found in the README.md file on GitHub.

# Dependencies Properties
vanishmod_version_range=[1.1,)